CRMIMMO/Controllers/ContratsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CRMIMMO.Models;

namespace CRMIMMO.Controllers
{
    public class ContratsController : Controller
    {
        private CRMContext22 db = new CRMContext22();

        // GET: Contrats
        public ActionResult Index()
        {
            var contrats = db.contrats.Include(c => c.Client);
            return View(contrats.ToList());
        }
        public ActionResult Searchcontrat(string ctt, string cin)
        {


            var searchcontrat = from d in db.contrats
                                where d.idcontrat == ctt
                                || d.ClientID == cin
                                select d;

            return View("Searchcontrat", searchcontrat.ToList());



        }
        // GET: Contrats/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contrat contrat = db.contrats.Find(id);
            if (contrat == null)
            {
                return HttpNotFound();
            }
            return View(contrat);
        }

        // GET: Contrats/Create
        public ActionResult Create()
        {
            ViewBag.ClientID = new SelectList(db.clients, "ClientID", "cin");
            return View();
        }

        // POST: Contrats/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idcontrat,idImmobilier,clientcin,datecontrat,ClientID")] Contrat contrat)
        {
            if (ModelState.IsValid)
            {
                db.contrats.Add(contrat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClientID = new SelectList(db.clients, "ClientID", "cin", contrat.ClientID);
            return View(contrat);
        }

        // GET: Contrats/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contrat contrat = db.contrats.Find(id);
            if (contrat == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClientID = new SelectList(db.clients, "ClientID", "cin", contrat.ClientID);
            return View(contrat);
        }

        // POST: Contrats/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idcontrat,idImmobilier,clientcin,datecontrat,ClientID")] Contrat contrat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contrat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClientID = new SelectList(db.clients, "ClientID", "cin", contrat.ClientID);
            return View(contrat);
        }

        // GET: Contrats/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contrat contrat = db.contrats.Find(id);
            if (contrat == null)
            {
                return HttpNotFound();
            }
            return View(contrat);
        }

        // POST: Contrats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Contrat contrat = db.contrats.Find(id);
            db.contrats.Remove(contrat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CRMIMMO/Controllers/ImmobiliersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CRMIMMO.Models;

namespace CRMIMMO.Controllers
{
    public class ImmobiliersController : Controller
    {
        private CRMContext22 db = new CRMContext22();

        // GET: Immobiliers
        public ActionResult Index()
        {
            return View(db.Immobiliers.ToList());
        }
        public ActionResult searchimmo(string type, string local, string Description)
        {
            var search = from d in db.Immobiliers
                         where d.typeImmobilierr == type
                         || d.localimmobilier == local
                         || d.description == Description
                         select d;

            return View("searchimmo", search.ToList());

        }

        // GET: Immobiliers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Immobilier immobilier = db.Immobiliers.Find(id);
            if (immobilier == null)
            {
                return HttpNotFound();
            }
            return View(immobilier);
        }

        // GET: Immobiliers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Immobiliers/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ImmobilierId,typeImmobilierr,localimmobilier,surfaceimmobilier,prix,description")] Immobilier immobilier)
        {
            if (ModelState.IsValid)
            {
                db.Immobiliers.Add(immobilier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(immobilier);
        }

        // GET: Immobiliers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Immobilier immobilier = db.Immobiliers.Find(id);
            if (immobilier == null)
            {
                return HttpNotFound();
            }
            return View(immobilier);
        }

        // POST: Immobiliers/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ImmobilierId,typeImmobilierr,localimmobilier,surfaceimmobilier,prix,description")] Immobilier immobilier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(immobilier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(immobilier);
        }

        // GET: Immobiliers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Immobilier immobilier = db.Immobiliers.Find(id);
            if (immobilier == null)
            {
                return HttpNotFound();
            }
            return View(immobilier);
        }

        // POST: Immobiliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Immobilier immobilier = db.Immobiliers.Find(id);
            db.Immobiliers.Remove(immobilier);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CRMIMMO/Views/Shared/_ControlSidebar.cshtml
<aside class="control-sidebar control-sidebar-dark">
    @* BEGIN Tabs *@
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    @* END Tabs *@
    <div class="tab-content">
        @* BEGIN Home Tab *@
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
            </ul>

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="pull-right-container">
                                <span class="label label-danger pull-right">70%</span>
                            </span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
        @* END Home Tab *@
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        @* BEGIN Settings Tab *@
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
            </form>
        </div>
        @* END Settings Tab *@
    </div>
</aside>
@* Add the sidebar's background. This div must be placed immediately after the control sidebar *@
<div class="control-sidebar-bg"></div>

CRMIMMO/Views/Shared/_Header.cshtml
<header class="main-header">
    @* BEGIN Logo *@
    <a href="@Url.Action("Index", "Home")" class="logo">
        @* Mini logo for sidebar 50x50 pixels *@
        <span class="logo-mini"><b>A</b>LT</span>
        @* Logo for regular state and mobile devices *@
        <span class="logo-lg"><b>CRM</b>IMMO</span>
    </a>
    @* END Logo *@
    @* BEGIN Header *@
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @* BEGIN Messages *@
              
                @* END Messages *@
                @* BEGIN Notifications *@
              
                @* END Notifications *@
                @* BEGIN Tasks *@
              
                @* END Tasks *@
                @* BEGIN User Account Menu *@
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="~/Content/img/user.jpg" class="user-image" alt="User Image">
                        <span class="hidden-xs">@User.Identity.Name</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="~/Content/img/user.jpg" class="img-circle" alt="User Image">

                            <p>
                                @User.Identity.Name - Web Developer
                                <small>Member since Nov @DateTime.Now.Year</small>
                            </p>
                        </li>
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <button>@Html.ActionLink("Log Off", "LogOff", "Account")</button>
                            </div>
                        </li>
                    </ul>
                </li>
                @* END User Account Menu *@
                @* BEGIN Control Sidebar Toggle Button *@
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
                @* END Control Sidebar Toggle Button *@
            </ul>
        </div>
    </nav>
</header>

CRMIMMO/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using WebHelpers.Mvc5.Enum
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        @if (!string.IsNullOrWhiteSpace(ViewBag.Title))
        {
            @ViewBag.Title@: -
        }
        AdminLTE
    </title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    @Styles.Render("~/Bundles/css")
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        @Html.Partial("_Header")
        @Html.Partial("_Sidebar")

        <div class="content-wrapper">
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.Description</small>
                </h1>
            </section>

            <section class="content">
                @RenderBody()
            </section>
        </div>

        @Html.Partial("_ControlSidebar")
    </div>

    <script src="@RouteJs.RouteJsHandler.HandlerUrl"></script>
    <script src="@EnumHandler.HandlerUrl"></script>
    @Scripts.Render("~/Bundles/js")
    @RenderSection("ViewSpecificJavascript", required: false)
</body>
</html>

CRMIMMO/Views/Shared/_Sidebar.cshtml
@using WebHelpers.Mvc5
<aside class="main-sidebar">
    <section class="sidebar">
        @* BEGIN Search *@
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        @* END Search *@
        @* BEGIN Menu *@
        @if (!User.Identity.IsAuthenticated)
        {
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">
                </li>
                <li class="@Url.IsLinkActive("Index", "Home")">
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-link"></i> <span>Home</span></a>
                </li>
                <li class="@Url.IsLinkActive("Clients", "Index")">
                    <a href="@Url.Action("Index", "Clients")"><i  class="fa fa-link"></i> <span>Clients</span></a>
                </li>
                <li class="@Url.IsLinkActive("immobiliers", "Index")">
                    <a href="@Url.Action("Index", "immobiliers")"><i class="fa fa-link"></i> <span>Immobilier</span></a>
                </li>
                <li class="@Url.IsLinkActive("contrats", "Index")">
                    <a href="@Url.Action("Index", "contrats")"><i class="fa fa-link"></i> <span>Contrats</span></a>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-link"></i> <span>Recherche</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="@Url.Action("searchcleint", "clients")">Recherche Clients</a></li>
                        <li><a href="@Url.Action("searchimmo", "Immobiliers")">Recherche Immobilies</a></li>
                        <li><a href="@Url.Action("Searchcontrat", "Contrats")">Recherche Contrats</a></li>

                    </ul>
                </li>
            </ul>
            @* END Menu *@
        }
        </section>
</aside>